config/routes.rb
Cuayolo::Application.routes.draw do

  
  get 'welcome' => 'welcome_home#index' #, as: :welcome
  get 'test' => 'test_apt#index'
  get 'dashboard' => 'dashboards#index'
  get 'avatar' => 'create_avatars#index'
  get 'logout' => 'sessions#destroy',  as: :logout
  get 'login' => 'sessions#new', as: :login 
  get 'signup' => 'users#new', as: :signup
  resources :users
  resources :sessions
  root 'home#index'

  

  

end

app/models/asignar_escuela.rb
class AsignarEscuela < ActiveRecord::Base
	belongs_to :user
	belongs_to :escuela
end

app/models/escuela.rb
class Escuela < ActiveRecord::Base
	has_many :asignarEscuelas
	has_many :users, through: :asignarEscuelas
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!


  has_one :asignarEscuela
  has_one :escuela, through: :asignarEscuela

  validates :username, :email, :password, :password_confirmation, :sexo, :fecha_nac, presence: true
  validates :username, :email, uniqueness: true

  validates_confirmation_of :password
  validates_presence_of :password, on: :create

  validates_format_of :email, :with => /\A(.+)@(.+)\.(.+)\z/

  #validates_format_of :fecha_nac, :with => /\A\d{2}\/\d{2}\/\d{4}\z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :default, :primary, :success, :info, :warning, :danger

  def not_authenticated
		redirect_to login_url, :alert => "Primer login de acceso a esta pagina"
	end
end

app/controllers/create_avatars_controller.rb
class CreateAvatarsController < ApplicationController
  def index
  	
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :require_login
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = login(params[:username], params[:password], params[:remember_me])
  	if user
  		redirect_back_or_to root_url, :notice => "Conectado!"
  	else
  		flash[:danger] = "Datos erroneos"
  		# render :new	
      redirect_back_or_to root_url
  	end	
  end

  def destroy
  	logout
  	redirect_to root_url, :notice => "Desconectado!"
  end
end

app/controllers/test_apt_controller.rb
class TestAptController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      flash[:success] ="Usuario #{@user.username} creado"
      redirect_to root_url

    else
      redirect_back_or_to root_url
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.permit( :username, :email, :password, :password_confirmation, :sexo, :fecha_nac )
    end
end

app/controllers/welcome_home_controller.rb
class WelcomeHomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_avatars_helper.rb
module CreateAvatarsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_apt_helper.rb
module TestAptHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_home_helper.rb
module WelcomeHomeHelper
end

app/views/create_avatars/index.html.erb
<h1>CreateAvatars#index</h1>
<p>Find me in app/views/create_avatars/index.html.erb</p>

app/views/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>

app/views/home/index.html.erb
<div id="container" class="container-fluid fontClass ">

  <div class="row-fluid">
  
    <div class="span10">
      <ul id="scene" class="scene">
        <li class="layer" data-depth="0.60"><%= image_tag(asset_url("estrellas1.png"), class: "estrellas") %></li>
        <li class="layer" data-depth="0.80"><%= image_tag(asset_url("galaxia1.png"), class: "pos_fixed_g2") %></li>
        <li class="layer" data-depth="0.30"><%= image_tag(asset_url("galaxia2.png"), class: "pos_fixed_g2") %></li>
      </ul>
    </div>

  
    <div class="signup">
    <%= form_tag users_path,  class: "hidden-sm hidden-xs form", role: "form" do %>

    <div class="form-group">
      <%= text_field_tag :username, nil, class: "form-control", placeholder: "Nombre de Usuario" %>
      
    </div>
    <div class="form-group">
      <%= text_field_tag :email, nil, class: "form-control", placeholder: "Correo Electrónico"%>
      
    </div>
    <div class="form-group">
      <%= password_field_tag :password, nil, class: "form-control", placeholder: "Contraseña" %>

    </div>
    <div class="form-group">
      <%= password_field_tag :password_confirmation, nil, class: "form-control", placeholder: "Confirmar contraseña"%>
      
    </div>
    <div class="form-group">
      <%= text_field_tag :sexo, nil, class: "form-control", placeholder: "Sexo"%>

    </div>
    <div class="form-group">

      <%= date_field_tag :fecha_nac, nil, placeholder: "dd/mm/aaaa" %>
    </div>


    <div class="actions"><%= submit_tag %></div>

    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cuayolo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <section class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Cuayolo", root_url, class: "navbar-brand" %>
    </section>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <section class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Casa", root_url %></li>
      </ul>
      
      <ul class="nav navbar-form navbar-right">
        <%= form_tag sessions_path, html: { role: "form", class: "form-inline" } do %>
          <article class="form-group">
            <%= text_field_tag :username, nil, class: "form-control input-sm", placeholder: "Nombre de usuario" %>
          </article>
          <article class="form-group">
            <%= password_field_tag :password, nil, class: "form-control input-sm", placeholder: "Contraseña" %>
          </article>
          <article class="form-group">
            <%= submit_tag "Entrar", class: "btn btn-sm btn-success" %>
            <article class="form-group visible-xs">
              <%= link_to "Registrarse", :login, class: "btn btn-sm btn-primary" %>
            </article>
          </article>
        <% end %>
      </ul>
    </section><!-- /.navbar-collapse -->
  </nav>

  <br><br><br>

  <section id="body" class="row">
    <% if flash.count > 0 %>
      <article id="row">
        <article class="col-md-9 col-md-push-1">
            <% flash.each do |name, msg| %>
              <%= content_tag :article, msg, :id => "flash_#{name}", class: "alert alert-#{name}" %>
            <% end %>
        </article>
      </article>
    <% end %>
  </section>

  <section class="row">
    <%= yield %>
  </section>
  

</body>
</html>

app/views/test_apt/index.html.erb
<h1>TestApt#index</h1>
<p>Find me in app/views/test_apt/index.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Bienvenido a Cuayolo</h1>
<p>Cuayolo es un proyecto creado para...</p>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Formulario invalido</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form role="form">
  <div class="form-group">
    <%= f.input_field :username, class: "form-control", placeholder: "Nombre de Usuario" %>
    
  </div>
  <div class="form-group">
    <%= f.input_field :email, class: "form-control", placeholder: "Correo Electrónico"%>
    
  </div>
  <div class="form-group">
    <%= f.input_field :password, class: "form-control", placeholder: "Contraseña" %>
    
  </div>
  <div class="form-group">
    <%= f.input_field :password_confirmation, class: "form-control", placeholder: "Confirmar contraseña"%>
    
  </div>
  <div class="form-group">
    <%= f.input_field :sexo, class: "form-control", placeholder: "Sexo"%>

  </div>
  <div class="form-group">
    <%= f.label :fecha_nac, placeholder: "fecha de nacimiento"%>
    <%= f.input :fecha_nac%>
  </div>


  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome_home/index.html.erb
<h1>WelcomeHome#index</h1>
<p>Find me in app/views/welcome_home/index.html.erb</p>